services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: mangamatcher
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - mangamatcher_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d mangamatcher" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:password@postgres:5432/mangamatcher
      PORT: "8000"
      FLASK_ENV: development
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    networks:
      - mangamatcher_network

  frontend:
    build:
      context: ./frontend
    depends_on:
      backend:
        condition: service_started
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    ports:
      - "3000:80"
    networks:
      - mangamatcher_network

volumes:
  postgres_data:


networks:
  mangamatcher_network:
